### ISSUE TITLE
data and run

### ISSUE THREAD

**Issue by SiqiMa7** [zhangtia16/LICAP#1]
Hello, I would like to know where is the data and how to make the code run?

**Comment by zhangtia16** [comment]
Thank you for your interest in our work.

Regarding the dataset: Our code is based on the RGTN code, so the dataset loading process is the same. TMDB5K and FB15K datasets can be obtained from https://github.com/GRAPH-0/RGTN-NIE. Simply place the relevant .pk files into the LICAP/datasets folder. The GA16K dataset was processed by ourselves following the data format of RGTN. It will also be released through cloud storage links in the future updates.

Regarding running the code: As I am currently busy with graduation, I have only uploaded the project's source code for now without providing a complete README. We will make reproduction easier through a complete README and code updates in the future.
